export interface Limitations{
    tonnage:string;
    voltage:string;
    scfmretmin :number,
    scfmretmax :number,
    scfmoutmin :number,
	scfmoutmax :number,
	espmin :number,
	espmax :number,
	eatdb1retmin :number,
	eatdb1retmax :number,
	eatdb1outmin :number,
	eatdb1outmax :number,
	eatwb1retmin :number,
	eatwb1retmax :number,
	eatwb1outmin :number,
	eatwb1outmax :number,
	gpmmin :number,
	gpmmax :number,
	eft1min :number,
	eft1max	:number,
	eatfmin	:number,
	eatfmax	:number,
	approxlatmin :number,
	approxlatmax :number,
	eft2min	:number,
	eft2max	:number,
	lftgpmmin :number,
	lftgpmmax :number,
	eatdb2min :number,
	eatdb2max :number,	
	eatwb2min :number,
	eatwb2max :number,
	eft3min	:number,
	eft3max	:number,
	btuhmin	:number,
	btuhmax :number
}